### ISSUE TITLE
Collect and make dead domains available

### ISSUE THREAD

**Issue by hagezi** [jarelllama/Blocklist-Checker#57]
@jarelllama 

You could benefit from checking for dead domains if you collect them and make them available for further checks.

If you make the dead domain list public, I would also use it in my project.

**Comment by jarelllama** [comment]
I did think about it but thought up of a couple of problems:

I can't push to this repo directly because then each workflow run has to wait for the previous to push before it can checkout.

Pushing to a separate repo would work. But maintaining a large dead domains file means I also have to check for resurrected domains which will take days to run. I currently do so for my own scam blocklist's dead cache and I'm getting about 500~ resurrected domains per day from my 7000 domain cache. 

If I collate dead domains without checking for resurrected, there will be many false positives over time.

Any thoughts?

**Comment by hagezi** [comment]
@jarelllama 
Yes, that's right.

Which I do on a monthly basis:

I check all my lists once a month for dead domains, these are added to a dead domains base list. The base list has grown over the months and currently contains 5 million domains.

This list is checked once a month for domains that are active again. This check now takes >10 days. The re-active domains are added to a "no longer dead" list.
This list is also checked once a month to see if it contains any dead domains.

I use these two lists to create a "clean" dead domains list, which is then applied to my lists during the build.
When creating the clean dead domains list, it is also taken into account that some "dead domains" must be excluded, as otherwise the compression of my lists suffers, meaning that countless subdomains end up on the lists.

I make my clean deadlist available afterwards. I have to split it because it is too big for Github. You are welcome to use it if you need it.

**Comment by jarelllama** [comment]
I would very much appreciate to use your list for this repo. An idea for integration could be to use the dead domains from blocklists checked here to supplement your list.

So whenever a new blocklist is checked, the dead domains can be pushed to separate repo where you can access it.

**Comment by jarelllama** [comment]
For my dead domains list, new dead are appended to the bottom, and the old entries at the top are pruned to cap the maximum number of entries.

**Comment by hagezi** [comment]
You will find the shared deadlist in the next release at https://github.com/hagezi/dns-blocklists/tree/main/share. I think it will be online in about 1.5 hours.

**Comment by hagezi** [comment]
@jarelllama deadlist is available
